### ISSUE TITLE
Make it work in the browser

### ISSUE THREAD

**Issue by aureooms** [runk/node-chardet#24]
It seems that the project does not rely too much on `node`'s API. I can only see two places where `node`'s API is used: `fs` is used to read files on the system (this is not allowed in the browser anyway), and `util` is used to do some inheritance stuff.

Does someone see another obstacle to making this compatible with browser usage?

**Comment by runk** [comment]
I think it's totally doable, just a usual problem with lack of time :)

**Comment by maximilize** [comment]
The same issue happens with react-native. How about moving `var fs = require('fs');` inside the specific functions where this module is really needed? Would be a quick and dirty fix.

**Comment by aureooms** [comment]
Copied from #25
> For the browser, is there not also an issue with the use of `Buffer`? It seems that the in-browser equivalent is [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array).

**Comment by aureooms** [comment]
Copied from #25

> If `Buffer` is only used in `fs.js` and the rest of the code is compatible with passing `Uint8Array` as parameter, then it should work in the browser too.

**Comment by runk** [comment]
Should be fixed as part of #27

**Comment by maximilize** [comment]
The metro bundler of react-native needs to import all required modules on build time. Since `require('fs')` appears somewhere in `index.js`, the bundler will fail:

```error: bundling failed: Error: Unable to resolve module `fs` from `node_modules/chardet/lib/index.js`: fs could not be found within the project.```

**Comment by aureooms** [comment]
One BREAKING solution would be to drop fs since it is only needed for convenience functions `detectFile` and `detectFileSync` which make the code longer and widen the scope of this package.

**Comment by aureooms** [comment]
Could split into two packages `chardet` and `node-chardet`.

**Comment by aureooms** [comment]
Or `chardet` and `libchardet`.

**Comment by aureooms** [comment]
One way to reimplement `detectFileSync` is as follows

```
export const bufferize = (filepath: string, start: int = 0, stop: int = -1): Buffer => {
  if (start > 0 || stop >= 0) { // one could interpret negative stop
    var fd = fs.openSync(filepath, "r");
    var size = stop - start;
    var buffer = Buffer.allocUnsafe(size);

    fs.readSync(fd, buffer, start, stop);
    fs.closeSync(fd);
    return buffer;
  }

  return fs.readFileSync(filepath);
}

var start = ...;
var stop = ...;
var buffer = bufferize(filepath, start, stop);
var encoding = detect(buffer);

**Comment by aureooms** [comment]
Also the use of type `Buffer` in the new TypeScript definitions is unnecessary. It seems you only rely on the `buffer[i]` and `buffer.length` which is something `Uint8Array` and other `Array`'s can also handle. `Buffer` does not exist in-browser. There should be a better way to specify you expect this interface.

**Comment by runk** [comment]
I'd appreciate a proper test for browser/native env, as a PR.

Personally I don't have much experience with this stuff.

**Comment by maximilize** [comment]
Sadly this issue is still not solved. I created my own fork with a working solution which can be found here: https://github.com/maximilize/node-chardet/commit/84f87899b449e6d15c0f4a013a4999b5d2b66266

I moved the code which is using the `fs` module to a separate file and re-implemented the `util.inherits` function which consists of 4 lines of code. Since this code needs to be put to a separate file (`fs.js`), this changes will break some API's since the filesystem functions needs to be imported via `require("chardet/fs")`.

**Comment by runk** [comment]
Great stuff @maximilize 👏 
If you'd send a PR I'd highly appreciate it

**Comment by maximilize** [comment]
My version is quite outdated, so I would need to redo my changes. I'll see when I have time to do this.

**Comment by maximilize** [comment]
Actually I did this work already in #25, but it got reverted in #26. Such a change **will** break the API of this lib, and the test cases need to be adjusted of course (what I forgot in the pull request). Feel free to use my old commit at #25 or https://github.com/maximilize/node-chardet/commit/84f87899b449e6d15c0f4a013a4999b5d2b66266 and fix the test cases there.

**Comment by runk** [comment]
Oh, right. I completely forgot about this change. 

Just looking thru code and not sure what's the current problem with browser-like env. 
- Loading file system is now on request rather than during startup: https://github.com/runk/node-chardet/blob/master/src/index.ts#L99 which should make it work in browser.
- `Inherits` is not a problem anymore with typescript - it produces shim code for class inheritance.

Can you please help to narrow down the issue?
